<<<<<<< HEAD
language: python
sudo: false
python:
  - "2.7"
branches:
  only:
    - detour/django-practice
install:
  - pip install -q Django=="1.8.5"
  - python setup.py -q install
env:
  - DJANGO_VERSION=1.8.5
script:
  - cd prepaw
  - ls
||||||| merged common ancestors
=======
language: python

sudo: false

python:
  - 2.7

env:
  - DJANGO_VERSION=1.8.5

branches:
  only:
    - detour/django-practice

before_install:
  - export DJANGO_SETTINGS_MODULE=prepaw.settings
  - export PIP_USE_MIRRORS=true
#  - export PYTHONPATH=$HOME/builds/oleyka/RedPaw

install:
# - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION --use-mirrors

script:
  - cd prepaw
  - python manage.py test

notifications:
  email:
    on_success: change
    on_failure: always
>>>>>>> detour/django-practice
