language: python

sudo: false

python:
  - 2.7

env:
  - DJANGO_VERSION=1.8.5

branches:
  only:
    - detour/django-practice

before_install:
  - export DJANGO_SETTINGS_MODULE=prepaw.settings
  - export PIP_USE_MIRRORS=true
#  - export PYTHONPATH=$HOME/builds/oleyka/RedPaw

install:
  - pip install -r requirements.txt

script:
  - cd prepaw
  - python manage.py test

notifications:
  email:
    on_success: change
    on_failure: always
