language: python

sudo: false

python:
  - 2.7

env:
  - DJANGO_VERSION=1.9

branches:
  only:
    - master

before_install:
  - export DJANGO_SETTINGS_MODULE=prepaw.settings
  - export DJANGO_DEBUG=true
  - export DJANGO_SECRET_KEY='00000000000000000000000000000000000000000000000000'
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION --use-mirrors

script:
  - cd prepaw
  - python manage.py test

notifications:
  email:
    on_success: change
    on_failure: always
