language: python

sudo: false

python:
  - '3.6'

addons:
  postgresql: '9.6'

env:
  - DJANGO_SETTINGS_MODULE=tutorial.settings DJANGO_DEBUG=true DJANGO_SECRET_KEY='00000000000000000000000000000000000000000000000000'

branches:
  only:
    - master

install:
  - pip install uwsgi  # install from packages outside of Travis
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE pollsdb;'
  - psql -U postgres -c "CREATE ROLE pollsuser WITH LOGIN PASSWORD 'pollspasswd';"
  - psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE "pollsdb" TO pollsuser;'
  - psql -U postgres -c 'ALTER USER pollsuser CREATEDB;'
  - cd prepaw && python manage.py migrate

script:
  - time tox

notifications:
  email:
    on_success: change
    on_failure: always
