language: python

sudo: false

python:
  - 2.7

env:
  - DJANGO_VERSION=1.9

branches:
  only:
    - master

before_install:
  - export DJANGO_SETTINGS_MODULE=prepaw.settings
  - export DJANGO_DEBUG=true
  - export DJANGO_SECRET_KEY='00000000000000000000000000000000000000000000000000'

install:
  - pip install uwsgi  # install from packages outside of Travis
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - time tox

notifications:
  email:
    on_success: change
    on_failure: always
