---
# ansible-playbook facts.yml -i hosts

- hosts: sites
  gather_facts: yes
  pre_tasks:
    - name: grab default git email
      local_action: command /usr/local/bin/git config user.email
      register: git_email
    - debug: var=git_email

  tasks:
    - name: snmp vars
      become: yes
      snmp_facts: host="{{ ansible_fqdn }}" version=v2c community=public
    - debug: var=hostvars[inventory_hostname]
