---

- include: letsencrypt.yml
  when: >
    ansible_os_family == 'FreeBSD' and
    ssl_source == 'letsencrypt'

- include: selfsign.yml
  when: >
    ansible_os_family == 'FreeBSD' and
    ssl_source == 'self'
