---

- name: install the web packages
  become: yes
  pkgng:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - postgresql94-server # includes the matching client
    - py27-pip
  when: ansible_os_family == 'FreeBSD'

# - include: nginx.yml
- include: uwsgi.yml
# - include: django.yml
