---

- name: install Heroku and prerequisites
  become: yes
  pkgng:
    name: "{{ item }}"
    state: present
  with_items:
    - py27-pip
    - py27-setuptools
    - py27-virtualenv
    - rubygem-heroku # includes ruby, libyaml and a dozen of other things
  when: ansible_os_family == 'FreeBSD'
