---

- name: install packages
  become: yes
  pkgng:
    name: "{{ item }}"
    state: present
  with_items:
    - net-snmp
    - py27-snmp4
  when: ansible_os_family == 'FreeBSD'

- name: add snmp config # edit me
  become: yes 
  copy:
    src: /usr/local/share/snmp/snmpd.conf.example
    dest: /usr/local/etc/snmp/snmp.conf
  when: false

- name: enable snmpd
  become: yes 
  service:
    name: snmpd
    enabled: yes 
  notify: start snmpd

- name: start snmpd
  become: yes 
  service:
    name: snmpd
    state: started
