---

- name: create self-signed SSL cert
  become: yes 
  command: >
    /usr/bin/openssl req -new -nodes -x509
    -subj "/C=US/ST=California/L=LosAltosHills/O=Self/CN={{ ansible_fqdn }}"
    -days 3650 -extensions v3_ca
    -keyout /etc/ssl/{{ ansible_fqdn }}-self.key
    -out /etc/ssl/{{ ansible_fqdn }}-self.crt
    creates=/etc/ssl/{{ ansible_fqdn }}-self.crt

- name: symlink self-signed certs to /etc/ssl
  become: yes 
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - src: /etc/ssl/{{ ansible_fqdn }}-self.crt
      dest: /etc/ssl/{{ ansible_fqdn }}.crt
    - src: /etc/ssl/{{ ansible_fqdn }}-self.key
      dest: /etc/ssl/{{ ansible_fqdn }}.key
