---

- name: install the web packages
  sudo: yes
  pkgng:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - uwsgi
    - py27-django
    - postgresql91-server # includes the matching client
  when: ansible_os_family == 'FreeBSD'
